### ISSUE TITLE
wicket 7 unsupported

### ISSUE THREAD

**Issue by kulik** [armhold/wicket-source-intellij#3]
java.lang.NoSuchMethodError: org.apache.wicket.Component.setMetaData(Lorg/apache/wicket/MetaDataKey;Ljava/lang/Object;)V
	at net.ftlines.wicketsource.AttributeModifyingInstantiationListener.onInstantiation(AttributeModifyingInstantiationListener.java:52)
	at org.apache.wicket.application.ComponentInstantiationListenerCollection$1.notify(ComponentInstantiationListenerCollection.java:38)
	at org.apache.wicket.application.ComponentInstantiationListenerCollection$1.notify(ComponentInstantiationListenerCollection.java:34)
	at org.apache.wicket.util.listener.ListenerCollection.notify(ListenerCollection.java:80)
	at org.apache.wicket.application.ComponentInstantiationListenerCollection.onInstantiation(ComponentInstantiationListenerCollection.java:33)
	at org.apache.wicket.Component.<init>(Component.java:687)
	at org.apache.wicket.MarkupContainer.<init>(MarkupContainer.java:120)
	at org.apache.wicket.Page.<init>(Page.java:170)
	at org.apache.wicket.Page.<init>(Page.java:134)
	at org.apache.wicket.markup.html.WebPage.<init>(WebPage.java:76)
	at org.apache.wicket.markup.html.pages.AbstractErrorPage.<init>(AbstractErrorPage.java:33)
	at org.apache.wicket.markup.html.pages.ExceptionErrorPage.<init>(ExceptionErrorPage.java:57)
	at org.apache.wicket.DefaultExceptionMapper.mapUnexpectedExceptions(DefaultExceptionMapper.java:175)
	at org.apache.wicket.DefaultExceptionMapper.internalMap(DefaultExceptionMapper.java:107)
	at org.apache.wicket.DefaultExceptionMapper.map(DefaultExceptionMapper.java:62)
	at org.apache.wicket.request.cycle.RequestCycle.handleException(RequestCycle.java:356)
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:233)
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:293)
	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:261)
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:203)
	at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:284)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1081)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1523)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by kulik** [comment]
I found other dependency that works compile "net.ftlines.wicket-source:wicket-source:7.0.0"
